---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker

inputs:
  - name: ert-concourse
  - name: tool-om
  - name: json_file

run:
  path: ert-concourse/ci/tasks/configure-ert.sh

params:
  pcf_iaas:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
  pcf_ert_ssl_cert:
  pcf_ert_ssl_key:
  pcf_az_1:
  pcf_az_2:
  pcf_az_3:
  terraform_template:
  terraform_prefix:
  # IaaS Specific
  gcp_proj_id:
  gcp_region:
  gcp_svc_acct_key:
  gcp_storage_access_key:
  gcp_storage_secret_key:
